### ISSUE TITLE
Systemctl issue on runit?

### ISSUE THREAD

**Issue by Zerogaku** [bayasdev/envycontrol#143]
hi when trying to swap to nvidia only i'm getting this message all of a sudden:
```
Switching to nvidia mode
Enable ForceCompositionPipeline: False
Enable Coolbits: False
Traceback (most recent call last):
  File "/usr/bin/envycontrol", line 33, in <module>
    sys.exit(load_entry_point('envycontrol==3.3.0', 'console_scripts', 'envycontrol')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/envycontrol.py", line 520, in main
    graphics_mode_switcher(args.switch, args.dm,
  File "/usr/lib/python3.11/site-packages/envycontrol.py", line 244, in graphics_mode_switcher
    service = subprocess.run(["systemctl", "enable", "nvidia-persistenced.service"],stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'systemctl'
```
is there anyway to fix this?

**Comment by ToneyFoxxy** [comment]
https://github.com/ToneyFoxxy/ToneyFoxxy-EnvyControl-Without-SystemD
