### ISSUE TITLE
[BUG] importlib.metadata.PackageNotFoundError: No package metadata was found for envycontrol

### ISSUE THREAD

**Issue by Arson31** [bayasdev/envycontrol#192]
**Describe the bug**
Ran pacman update this morning to update my packages. I later shutdown the machine and turned it on later in the afternoon. I logged in and saw the below error message in the notification panel in plasma.

```
Traceback (most recent call last):
File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 407, in from_name
return next(iter(cls.discover(name=name)))
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/bin/envycontrol", line 33, in
sys.exit(load_entry_point(envycontrol==3.5.1, console_scripts, envycontrol)())
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/envycontrol", line 22, in importlib_load_entry_point
for entry_point in distribution(dist_name).entry_points
~~~~~~~~~~~~^^^^^^^^^^^
File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 960, in distribution
return Distribution.from_name(distribution_name)
~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 409, in from_name
raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for envycontrol
Traceback (most recent call last):
File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 407, in from_name
return next(iter(cls.discover(name=name)))
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/bin/envycontrol", line 33, in
sys.exit(load_entry_point(envycontrol==3.5.1, console_scripts, envycontrol)())
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/envycontrol", line 22, in importlib_load_entry_point
for entry_point in distribution(dist_name).entry_points
~~~~~~~~~~~~^^^^^^^^^^^
File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 960, in distribution
return Distribution.from_name(distribution_name)
~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 409, in from_name
raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for envycontrol
```

**To Reproduce**
1. Run `sudo envycontrol -s nvidia`
2. See error

```
Traceback (most recent call last):
File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 407, in from_name
return next(iter(cls.discover(name=name)))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/envycontrol", line 33, in <module>
sys.exit(load_entry_point('envycontrol==3.5.1', 'console_scripts', 'envycontrol')())
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/envycontrol", line 22, in importlib_load_entry_point
for entry_point in distribution(dist_name).entry_points
~~~~~~~~~~~~^^^^^^^^^^^
File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 960, in distribution
return Distribution.from_name(distribution_name)
~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 409, in from_name
raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for envycontrol
```

**Expected behavior**
No errors at startup & no errors after entering `envycontrol` in the terminal.

**System Information:**
 - Model: OMEN by HP Laptop 15-dc1xxx
 - Distro: Garuda Linux x86_64
 - Kernel: 6.6.67-1-lts
 - DE/WM and Display Manager (if applicable): KDE Plasma 6.2.4/KWin (X11)
 - EnvyControl version: 3.5.1
 - Nvidia driver version: 565.77
 - lspci output:
```
00:00.0 Host bridge: Intel Corporation 8th Gen Core Processor Host Bridge/DRAM Registers (rev 07)
00:01.0 PCI bridge: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) (rev 07)
00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 07)
00:12.0 Signal processing controller: Intel Corporation Cannon Lake PCH Thermal Controller (rev 10)
00:14.0 USB controller: Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller (rev 10)
00:14.2 RAM memory: Intel Corporation Cannon Lake PCH Shared SRAM (rev 10)
00:16.0 Communication controller: Intel Corporation Cannon Lake PCH HECI Controller (rev 10)
00:17.0 RAID bus controller: Intel Corporation 82801 Mobile SATA Controller [RAID mode] (rev 10)
00:1d.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #9 (rev f0)
00:1d.5 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #14 (rev f0)
00:1d.6 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #15 (rev f0)
00:1d.7 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #16 (rev f0)
00:1f.0 ISA bridge: Intel Corporation HM470 Chipset LPC/eSPI Controller (rev 10)
00:1f.3 Audio device: Intel Corporation Cannon Lake PCH cAVS (rev 10)
00:1f.4 SMBus: Intel Corporation Cannon Lake PCH SMBus Controller (rev 10)
00:1f.5 Serial bus controller: Intel Corporation Cannon Lake PCH SPI Controller (rev 10)
01:00.0 VGA compatible controller: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)
02:00.0 Non-Volatile memory controller: Toshiba Corporation XG6 NVMe SSD Controller
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet Controller (rev 16)
04:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8822BE 802.11a/b/g/n/ac WiFi adapter
05:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS522A PCI Express Card Reader (rev 01)
```

**Comment by bayasdev** [comment]
This happens all the time when there's a major Python update in Arch, try clearing Pacman cache and reinstalling envycontrol :)

**Comment by Arson31** [comment]
I ran the commands below and rebooted my machine:
```
paccache -rk0
sudo pacman -S envycontrol
```
I'm receiving the same error message after reboot:
```
sudo envycontrol -s nvidia
Traceback (most recent call last):
File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 407, in from_name
return next(iter(cls.discover(name=name)))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/envycontrol", line 33, in <module>
sys.exit(load_entry_point('envycontrol==3.5.1', 'console_scripts', 'envycontrol')())
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/envycontrol", line 22, in importlib_load_entry_point
for entry_point in distribution(dist_name).entry_points
~~~~~~~~~~~~^^^^^^^^^^^
File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 960, in distribution
return Distribution.from_name(distribution_name)
~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 409, in from_name
raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for envycontrol
```

**Comment by bayasdev** [comment]
> I ran the commands below and rebooted my machine:
> 
> ```
> 
> paccache -rk0
> 
> sudo pacman -S envycontrol
> 
> ```
> 
> I'm receiving the same error message after reboot:
> 
> ```
> 
> sudo envycontrol -s nvidia
> 
> Traceback (most recent call last):
> 
> File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 407, in from_name
> 
> return next(iter(cls.discover(name=name)))
> 
> StopIteration
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> 
> Traceback (most recent call last):
> 
> File "/usr/bin/envycontrol", line 33, in <module>
> 
> sys.exit(load_entry_point('envycontrol==3.5.1', 'console_scripts', 'envycontrol')())
> 
> ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> File "/usr/bin/envycontrol", line 22, in importlib_load_entry_point
> 
> for entry_point in distribution(dist_name).entry_points
> 
> ~~~~~~~~~~~~^^^^^^^^^^^
> 
> File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 960, in distribution
> 
> return Distribution.from_name(distribution_name)
> 
> ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
> 
> File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 409, in from_name
> 
> raise PackageNotFoundError(name)
> 
> importlib.metadata.PackageNotFoundError: No package metadata was found for envycontrol
> 
> ```

@Arson31 try doing `sudo pacman -R envycontrol` before reinstalling

**Comment by Arson31** [comment]
@bayasdev 
1. `sudo pacman -R envycontrol`
2. reboot
3. `sudo pacman -S envycontrol`
4. reboot again
5. `sudo envycontrol -s nvidia`

same error message

**Comment by heyGio** [comment]
It worked for me using yay! (Clean built all the packages when asked)

**Comment by Arson31** [comment]
Pacman update of Envycontrol-3.5.1-1 solved the problem.
